fix(select): classModifier and forceDisplayPlaceholder
AxaGuilDEv/react-toolkit pull request #1013
Opened 2023-02-15 13:41 UTC by samuel-gomez

## Related issue

### Reference to the issue

fix #1012 
fix #1008 

### Description of the issue

Fix for apply classModifier on select field
Fix for display placeholder with forceDisplayPlaceholder

### Person(s) for reviewing proposed changes

@SamuelHsn @johankorger 

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

2023-02-15 14:02 UTC, SamuelHsn requested changes

2023-02-15 14:02 UTC, SamuelHsn commented on packages/Form/Input/select/src/Select.tsx
> +    : options;
suggestion : `const newOptions = hasHandleChangeOnce
    ? options
    : [{ value: '', label: placeholder }, ...options];`

2023-02-15 15:00 UTC, samuel-gomez commented on packages/Form/Input/select/src/Select.tsx
>          setHasHandleChangeOnce(!forceDisplayPlaceholder);
non car la valeur de forceDisplayMessage n'est définie qu'une seule fois depuis les props

2023-02-15 15:00 UTC, samuel-gomez commented on packages/Form/Input/select/src/Select.tsx
>          setHasHandleChangeOnce(!forceDisplayPlaceholder);
elle permet justement de donner la main au consommateur de garder ou pas le placeholder

2023-02-15 15:28 UTC, samuel-gomez commented on packages/Form/Input/select/src/Select.tsx
> +    : options;
@SamuelHsn,  done

2023-02-15 15:58 UTC, SamuelHsn commented on packages/Form/Input/select/src/Select.tsx
>          setHasHandleChangeOnce(!forceDisplayPlaceholder);
Ah oui en effet j'ai mal désolé

2023-02-15 16:01 UTC, SamuelHsn approved these changes

2023-02-16 08:33 UTC, johankorger approved these changes

2023-02-16 08:35 UTC, merged