Migrate collapse package to Typescript
AxaGuilDEv/react-toolkit pull request #644
Opened 2020-06-27 16:21 UTC by arnaudforaison

### Description of the issue

To have all toolkit's packages written in Typescript, this PR migrate collapse package

# Important

* Class component are rewritten in functional component
* Component use hooks
* Others expects are made for CollapseCardBase because instance doesn't work with React 16.x and functional component

2020-07-07 11:55 UTC, xballoy submitted a review, later dismissed
LGTM

2020-07-20 07:30 UTC, guillaume-chervet submitted a review, later dismissed

2020-09-02 13:21 UTC, romuleald requested changes

2020-09-02 13:21 UTC, romuleald commented on packages/collapse/src/CollapseCardBase.tsx
> +
ligne en trop :)

2020-09-02 13:21 UTC, romuleald commented on packages/collapse/src/__snapshots__/Body.spec.tsx.snap
> +  id="idBody"
**Question :** à quoi sert cet `id` ?

2020-09-02 13:21 UTC, romuleald commented on packages/collapse/src/Header.tsx
> +  const componentClassName = ClassManager.getComponentClassName(
```suggestion

  const componentClassName = ClassManager.getComponentClassName(
```

2020-09-02 13:21 UTC, romuleald commented on packages/collapse/src/Header.tsx
> +export type HeaderToggleElement = {
```suggestion

export type HeaderToggleElement = {
```

2020-09-02 13:21 UTC, romuleald commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
**question :** cette valeur ne devrait-elle pas être dynamique ?

2020-09-02 13:23 UTC, samuel-gomez-axa commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
tu parles aria-expended ? oui je pense

2020-09-02 13:27 UTC, samuel-gomez-axa commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
un exemple : http://3needs.org/en/testing/code/aria-expanded.html#

2020-09-02 13:29 UTC, arnaudforaison commented on packages/collapse/src/Header.tsx
> +  const componentClassName = ClassManager.getComponentClassName(
Pas compris le changement

2020-09-02 13:29 UTC, arnaudforaison commented on packages/collapse/src/Header.tsx
> +export type HeaderToggleElement = {
Pas compris le changement

2020-09-02 13:31 UTC, arnaudforaison commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
C'était déjà à true. Vous voulez une valuer par défaut à true mais aussi une prop ?

2020-09-02 15:05 UTC, arnaudforaison commented on packages/collapse/src/__snapshots__/Body.spec.tsx.snap
> +  id="idBody"
En fait dans mon test j'avais rajouté l'id mais je l'enlève

2020-09-02 15:07 UTC, romuleald commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
Si la valeur est true dans le composant est fermé, c'est invalide

2020-09-02 15:11 UTC, samuel-gomez-axa commented on packages/collapse/src/Header.tsx
> +          aria-expanded="true"
la valeur doit changer en fonction de l'état ouverture/fermeture

2020-10-11 16:40 UTC, arnaudforaison commented
Need some reviewers

2020-10-12 15:05 UTC, xballoy commented on packages/collapse/src/Accordion.spec.ts
> +    let oldCollapses = [false];
const instead of let?

2020-10-12 15:06 UTC, xballoy approved these changes
LGTM.
Can you rebase with master and push again?

2020-10-16 08:40 UTC, bernard-arnaud approved these changes

2020-10-16 08:55 UTC, romuleald approved these changes

2020-10-16 08:58 UTC, merged