fix(tabs): init tabs with custom active index other than zero
AxaGuilDEv/react-toolkit pull request #677
Opened 2020-09-09 08:20 UTC by remija

## Related issue

Unable to activate index upper than zero (default) when init Tabs component

### Reference to the issue

`Here you can add link to related issue`

### Description of the issue

It is impossible to display particular tab other than 0 index when showing Tabs component

### Person(s) for reviewing proposed changes

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

2020-09-09 12:57 UTC, sisko59 submitted a review, later dismissed

2020-09-09 12:58 UTC, sisko59 commented
Félicitations pour cette première PR 🥇

2020-09-09 14:22 UTC, romuleald commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
**Question :** Comment ça se fait que l'on passe sur un `div` ici ?

2020-09-09 14:22 UTC, romuleald commented on packages/tabs/src/Tab.tsx
>  import * as React from 'react';
**thought :** tu n'as rien changé à part l'indent', tu devrais peut-être supprimer cette modif'

2020-09-09 14:22 UTC, romuleald commented on packages/tabs/src/TabsCore.tsx
>        onChange={onChangeEvent(onChange)(setState)(state)}
**suggestion :** on pourrait peut-être renommer `onChangeEvent` en `setActiveIndex`

2020-09-09 14:22 UTC, romuleald commented on packages/tabs/src/TabsCore.tsx
> +    initialState.activeIndex = activeIndex;
**question :** Pourquoi `initialState` est un objet ? On n'utilise que la clé dedans `activeIndex`
La possibilité de mutation est un risque de dysfonctionnement, si on a besoin d'un autre state on pourra toujours à l'avenir faire un autre `useState`

2020-09-09 14:33 UTC, romuleald requested changes

2020-09-09 14:33 UTC, romuleald commented on packages/tabs/src/TabsCore.tsx
> +    initialState.activeIndex = activeIndex;
En fait c'est un risque majeur, `initialState` étant une référence de l'objet `defaultState`, celle-ci étant global au module `TasbCore.tsx` sera commune à tous les appels à ce composant, donc un bug potentiel quand il y a 2 fois le composant dans la page.

2020-09-10 06:30 UTC, samuel-gomez-axa commented on packages/tabs/src/TabsCore.tsx
> +      activeIndex={state.activeIndex}
au final, ce n'est pas vraiment stateless, non ? pour que ça le soit , il faudrait que TabsStateLess reçoive juste activeIndex et une fonction de changement , selon moi il faut faudrait remonter la gestion de l'état dans un composant parent, qu'en penses-tu ?

2020-09-10 06:40 UTC, remija commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Honnetement je ne sais pas car je n'ai pas modifié ce composant :) J'ai juste remarqué qu'un TU sur celui-ci ne passait pas et j'ai juste mis à jour le snapshot (Il parait qu'il y a une autre PR à ce sujet).

2020-09-10 07:12 UTC, remija commented on packages/tabs/src/Tab.tsx
>  import * as React from 'react';
ok

2020-09-10 07:14 UTC, remija commented on packages/tabs/src/TabsCore.tsx
> +    initialState.activeIndex = activeIndex;
j'ai fait en sorte que "activeIndex" soit l'état (ce n'est plus un objet). La prop "activeIndex" est obligatoire avec une valeur par défaut à 0.

2020-09-10 07:19 UTC, remija commented on packages/tabs/src/TabsCore.tsx
>        onChange={onChangeEvent(onChange)(setState)(state)}
pas chaud pour faire ce renommage car le `onChangeEvent` permet de base de modifier le activeIndex mais permet aussi d'exécuter une fonction supplémentaire (paramètre `onChange`)

2020-09-10 07:39 UTC, sisko59 commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Oui, il y a un problème actuellement avec ce test, qui fonctionne différemment entre nos poste et la build.
De mon coté pour que ma PR build, j'ai forcé exceptionnellement mon push sans la mise à jour de la snapshot car ça ne me concerné pas.

2020-09-10 07:54 UTC, youf-olivier commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Le soucis des tests est en cours d'investigation, c'est un soucis entre lerna et la CI

2020-09-10 07:54 UTC, romuleald commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Ha oui, je pensais que c'était résolu ce souci… En l'état il faudrait attendre la correction de ce problème

2020-09-10 07:55 UTC, youf-olivier commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Guillaume et Arnaud s'y sont cassé les dents pour le moment...

2020-09-10 07:56 UTC, romuleald commented on packages/tabs/src/TabsCore.tsx
>        onChange={onChangeEvent(onChange)(setState)(state)}
Une fonction devrait toujours être nommé en fonction de ce qu'elle fait et pas comment elle est appelé :)
Ce n'est pas le sujet de la PR donc c'est pas grave si on ne le fait pas maintenant

2020-09-10 07:59 UTC, remija commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Qu'est-ce que je fais dans ce cas ? Je pousse le snapshot modifié ou pas ?

2020-09-10 08:01 UTC, youf-olivier commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
Pousse pas le help en effet, j'ai voulu le pousser aussi (j'ai le meme soucis sur ma PR), pousse que ce qui a été directement impacté par ta PR

2020-09-10 08:08 UTC, remija commented on packages/help/src/__snapshots__/Help.spec.js.snap
> +<div
ok, done.

2020-09-10 17:13 UTC, romuleald approved these changes

2020-09-11 06:47 UTC, youf-olivier approved these changes

2020-09-11 06:49 UTC, samuel-gomez-axa submitted a review, later dismissed

2020-09-11 07:02 UTC, guillaume-chervet submitted a review, later dismissed
beau boulot merci !

2020-09-11 08:58 UTC, guillaume-chervet approved these changes

2020-09-11 09:12 UTC, samuel-gomez-axa approved these changes

2020-09-11 11:53 UTC, merged