Update dependencies & moment
AxaGuilDEv/react-toolkit pull request #722
Opened 2020-10-15 16:46 UTC by arnaudforaison

Refer to any issues

2020-10-16 04:59 UTC, guillaume-chervet submitted a review, later dismissed
Nice arnaud

2020-10-20 11:54 UTC, xballoy submitted a review, later dismissed

2020-10-20 15:37 UTC, xballoy commented on package.json
> +    "pre-commit": "1.2.2",
I removed pre-commit, it override husky configuration

2020-10-20 15:38 UTC, xballoy requested changes
Can you remove pre-commit from the package.json, it override husky configuration

2020-10-21 07:01 UTC, xballoy approved these changes

2020-10-21 07:42 UTC, youf-olivier approved these changes
Je vais bientot le virer mais au moins d'ici là ca sera a jour :D

2020-10-21 07:48 UTC, merged