feat(collapse): added onToggleCallback prop on CollapseCardBase
AxaGuilDEv/react-toolkit pull request #727
Opened 2020-10-16 15:07 UTC by bernard-arnaud

## Related issue

### Reference to the issue

[721](https://github.com/AxaGuilDEv/react-toolkit/issues/721)

### Description of the issue

Accordion rewrites onToggle for CollapseCardBase, a possible solution is to add a callback function props  that would be called after onToggle

### Person(s) for reviewing proposed changes

`You can add @mention here`

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

2020-10-19 07:19 UTC, xballoy approved these changes

2020-10-19 12:31 UTC, xballoy commented
@bernard-arnaud can you rebase with master and push again to fix your CI issues?

2020-10-20 10:13 UTC, xballoy commented
@bernard-arnaud tu as un conflit, les stories ont été déplacées à coté des composants. Tu peux corriger et repush ? Merci !

2020-10-20 12:08 UTC, xballoy submitted a review, later dismissed

2020-10-20 12:25 UTC, youf-olivier requested changes
Je met en request Changes, y a des trucs qui me chagrinent.

Le temps de montrer ce qui me gène je la bloque :)

2020-10-20 12:48 UTC, youf-olivier requested changes
La correction doit se faire au niveau de l'accordeon. 

Le but sera de mixer ta callback avec celle de l'accordeon dans lequel tu as : 

```javascript
export const AccordionBase = ({
  children,
  className,
  classModifier,
  handleToggle,
  collapses,
}: Props) => {
  const renderedChildren = React.Children.map(children, (child, index) => {
    return React.cloneElement(child, {
      ...child.props,
      index,
      onToggle: handleToggle,
      collapse:
        collapses[index] !== undefined
          ? collapses[index]
          : child.props.collapse,
      className: child.props.className,
      classModifier: child.props.classModifier,
    });
  });
  const componentClassName = ClassManager.getComponentClassName(
    className,
    classModifier,
    defaultClassName
  );
  return (
    <div
      className={componentClassName}
      role="tablist"
      aria-multiselectable="true">
      {renderedChildren}
    </div>
  );
};
```

Là on a deux choix. 

Soit on choisi un des deux : 

```javascript
      onToggle: child.props.onToggle || handleToggle,
```

Soit on peut mixer et appeler les deux. Dans le style (Je dis bien le style, j'écris ça vite fais)
```javascript
const mixCallback = (
  funcA: (e: HeaderToggleElement) => void,
  funcB: (e: HeaderToggleElement) => void
) =>  (e: HeaderToggleElement) =>{
  funcA(e);
  funcB(e);
};
// Plus loin
 onToggle: mixCallback(child.props.onToggle, handleToggle),
```

Ou alors on peut passer un tableau de callback... Ici apres la solution est open.

Si j'arrive a faire tourner le storybook (qui est pas gagné) je regarderai la meilleure solution selon moi, mais en l'état je pense qu'on peut revoir le truc. 

Qu'en pensez vous ?

2020-10-20 12:48 UTC, youf-olivier commented on packages/collapse/src/Header.tsx
> +  }
Ca clairement ça me choque. 

On a une grosse duplication. Pour moi le soucis doit pas se corriger ici.

2020-10-20 13:16 UTC, xballoy commented on packages/collapse/src/Header.tsx
> +  }
C'est vrai que c'est plus propre comme ca. Sinon pour le storybook ca devrait fonctionner sans problème maintenant que la PR pour les migrer avec les composants est passée

2020-10-20 15:19 UTC, youf-olivier commented
Je viens de tester la méthode de mixage des fonctions. Elle permet d'utiliser le composant comme tu voulais l'utiliser à la base : 

```javascript
<Accordion
    classModifier={text('classModifier', '')}
    className={text('className', '')}
    onlyOne={boolean('onlyOne', true)}>
    <CollapseCardBase
      id="idcollaspe1"
      onToggle={action('onToggle')}>
      <CollapseCard.Header>
        {text(KNOBS_LABELS.collapse1.title, LABELS.collapse1.title)}
      </CollapseCard.Header>
      <CollapseCard.Body>
        {text(KNOBS_LABELS.collapse1.text, LABELS.collapse1.text)}
        <b>{text(KNOBS_LABELS.collapse1.textb, LABELS.collapse1.textb)}</b>
      </CollapseCard.Body>
    </CollapseCardBase>
  </Accordion>
```

![image](https://user-images.githubusercontent.com/40664502/96607237-72ac0e80-12f8-11eb-82a2-7da2f4d9da03.png)

2020-10-21 08:51 UTC, xballoy approved these changes

2020-10-21 08:55 UTC, youf-olivier approved these changes

2020-10-21 08:55 UTC, youf-olivier commented
Good Job

2020-10-21 08:57 UTC, xballoy commented
Tu as des erreurs de lint https://dev.azure.com/axaguildev/react-toolkit/_build/results?buildId=3402&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=1015

2020-10-21 09:21 UTC, youf-olivier commented
étrange, y a pas un précommit hook ?

2020-10-21 09:27 UTC, xballoy commented
Si il y a un hook, il ne se lancait pas avant mais j'ai fixé ca dans une autre PR qui a été mergée.

2020-10-21 09:33 UTC, youf-olivier approved these changes

2020-10-21 09:37 UTC, xballoy approved these changes

2020-10-21 09:51 UTC, xballoy commented
@youf-olivier @arnaudforaison vous pouvez merger car Sonar ne passera jamais (c'est un fork)

2020-10-21 10:03 UTC, merged