feat(modal): improve a11y on Modal
AxaGuilDEv/react-toolkit pull request #772
Opened 2020-10-26 07:52 UTC by youf-olivier

J'ai ajouté aria label et aria modal via des props de modal.

En parallèle j'ai ouvert une PR sur React Modal : https://github.com/reactjs/react-modal/pull/835 pour ajouter le aria modal par défaut pour suivre les préco W3C

J'en ai profité pour migrer la Boolean Modal sur TypeScript et migrer les Stories vers le nouveau format

(woops j'ai oublié de migrer la story de Modal Default)

2020-10-26 08:17 UTC, xballoy requested changes

2020-10-26 08:17 UTC, xballoy commented on packages/Modal/boolean/package.json
> +  "types": "dist/index.d.ts",
Tu peux supprimer "prop-types" comme tu as migré en TS

2020-10-26 08:49 UTC, youf-olivier commented on packages/Modal/boolean/package.json
> +  "types": "dist/index.d.ts",
Done

2020-10-26 15:51 UTC, xballoy approved these changes

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +import * as PropTypes from 'prop-types';
Prop- types n'est plus en dépendance

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +import Modal, { HeaderProps } from '@axa-fr/react-toolkit-modal-default';
HeaderProps doit être déduit du composant, comme ceci
`ComponentProps<Modal.Header>`

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +interface ModalBooleanCoreProps {
Ce doit être une composition de type.
`type ModalBooleanCoreProps = Partial<typeof defaultProps> & {
isOpen: boolean,
On submit,
OnCancel
}
`

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +export type ModalBooleanProps = HeaderProps &
Ce type ne devrait pas être exporté
Et cf remarque HeaderProps au dessus

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +const ModalBoolean: React.FC<ModalBooleanProps> = ({
Il est préférable de typer les propos plutôt que de typer le composant

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +  const onCancelcb = () => {
Plutôt mettre une valeur par défaut à la fonction dans les defaultProps
Idem pour le onSubmit

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/default/src/Div.tsx
> +const Div: React.FC<DivProps> = props => (
Idem typer l'objet propos plutôt que de retourner un composant react typé

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/default/src/ModalDefault.stories.tsx
> +import { ModalCoreProps } from '../dist';
Doit être déduit et pas importé depuis dist

2020-10-27 06:47 UTC, arnaudforaison commented on packages/Modal/default/src/ModalCore.tsx
> +  title?: string;
Les defaultProps doivent être déduites de l'objet
`Partial<typeof defaultProps>`

2020-10-27 08:04 UTC, youf-olivier commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +import Modal, { HeaderProps } from '@axa-fr/react-toolkit-modal-default';
Hmmm ça marche pô. Faudrait que tu m'explique. Je te call après

2020-10-27 08:06 UTC, youf-olivier commented on packages/Modal/boolean/src/ModalBoolean.tsx
> +import Modal, { HeaderProps } from '@axa-fr/react-toolkit-modal-default';
ok c'etait ```ComponentProps<typeof Modal.Header>```

2020-10-27 17:09 UTC, xballoy commented
Tu as 1 test KO

2020-10-27 20:47 UTC, youf-olivier commented
Je m'en doutais :D

2020-10-27 21:10 UTC, xballoy commented
Encore un ^^

2020-10-28 13:42 UTC, xballoy approved these changes

2020-10-28 13:46 UTC, arnaudforaison approved these changes

2020-10-28 13:46 UTC, merged