Feature/number use input number
AxaGuilDEv/react-toolkit pull request #784
Opened 2020-10-30 14:44 UTC by johnmeunier

## Related issue

### Reference to the issue

Fixes #710

- Replace the input type text used in the Number component by a native input type number
- The story is now stateful
- The viewValue and the value has now the same value

2020-10-30 14:58 UTC, xballoy approved these changes

2020-10-30 14:58 UTC, xballoy commented on packages/Form/Input/number/src/Number.js
> +  viewValue,
Le viewValue est obligatoire dans les PropTypes, on ne le rendrait pas facultatif comme il ne sert à rien

2020-10-30 14:58 UTC, xballoy commented on packages/Form/Input/number/src/NumberInput.stories.js
>  import readme from '../README.md';
Dans le readme on explique la différence viewValue / value ?

2020-10-30 15:15 UTC, johnmeunier commented on packages/Form/Input/number/src/Number.js
> +  viewValue,
J'ai viré la prop viewValue. Je cite "ne pas avoir peur des breakings changes" :D

2020-10-30 15:46 UTC, xballoy requested changes
Ajouter un fichier MIGRATION.md

2020-10-30 16:33 UTC, guillaume-chervet commented
@djaumes, Cette pullRequest change un comportement UX.
Dans les règles UX historique, l'utilisateur n'est jamais bloqué sur la saisie d'un chiffre ou lettre.
même s'il tape : "12r33" dans le champ, cela apparait dans le champ de saisie. 
C'est le message d'erreur qui indique ensuite à l'utilisateur que la saisie n'est pas valide.

Par default se composant accepte les . et les , comme séparateur.

C'était le comportement historique qui est par défaut sur tout les champs type date, number, etc.

Dans le vieux document de référence de la cop front:
![image](https://user-images.githubusercontent.com/52236059/97731110-08078980-1ad5-11eb-96be-d4f0f37b828e.png)

Cette PR change un comportement, via l'utilisation d'un champs type Number html. 
Ce n'est pas anodin c'est un vrai choix UX. Le champ aura le comportement du champ type Number HTML classique : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/number

Si l'utilisateur saisi  : "12r33", le champ affichera 1233.

![image](https://user-images.githubusercontent.com/52236059/97731222-28cfdf00-1ad5-11eb-9bf2-0e39401f89b9.png)

Je pense que se serait super de prendre un choix et de le documenter.

2020-11-02 07:21 UTC, johnmeunier commented on packages/Form/Input/number/src/NumberInput.stories.js
>  import readme from '../README.md';
J'ai ajouté le fichierr readme

2020-11-02 07:29 UTC, johnmeunier commented
> @djaumes, Cette pullRequest change un comportement UX.
> Dans les règles UX historique, l'utilisateur n'est jamais bloqué sur la saisie d'un chiffre ou lettre.
> même s'il tape : "12r33" dans le champ, cela apparait dans le champ de saisie.
> C'est le message d'erreur qui indique ensuite à l'utilisateur que la saisie n'est pas valide.
> 
> Par default se composant accepte les . et les , comme séparateur.
> 
> C'était le comportement historique qui est par défaut sur tout les champs type date, number, etc.
> 
> Dans le vieux document de référence de la cop front:
> ![image](https://user-images.githubusercontent.com/52236059/97731110-08078980-1ad5-11eb-96be-d4f0f37b828e.png)
> 
> Cette PR change un comportement, via l'utilisation d'un champs type Number html.
> Ce n'est pas anodin c'est un vrai choix UX. Le champ aura le comportement du champ type Number HTML classique : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/number
> 
> Si l'utilisateur saisi : "12r33", le champ affichera 1233.
> 
> ![image](https://user-images.githubusercontent.com/52236059/97731222-28cfdf00-1ad5-11eb-9bf2-0e39401f89b9.png)
> 
> Je pense que se serait super de prendre un choix et de le documenter.

Comme il y aura potentiellement des breakings change, cette PR partira dans une v2.0.0.
On perd cette feature mais on sera rapproche du comportement habituel dans HTML, que tout le monde connait. C'est à dire que si tu tapes une lettre dans un champ texte, rien ne se passe. 
On gagne également le changement de clavier sur mobile et la simplication du code.

2020-11-02 11:28 UTC, djaumes commented
@johnmeunier @guillaume-chervet 
Aucun problème pour moi d'aller vers du natif, surtout si cela permet d'éviter des générations d'erreurs/re-saisies utilisateur.

Nous avions rédigé la règle suivante sur les champs avec des formats de données:
Format de donnée imposée (mail) - Renvoie une erreur si le format de donnée ne correspond pas [section 4/f/](https://axaguildev.github.io/design-system/organisms/form/)

Ce format de données peut être un mail comme un nombre ou une date(il faudrait que je modifie le texte!), il faut garder cette cohérence de règle au delà du nouveau comportement.

J'ai remarqué que sur Safari la démo mozilla ne fonctionne pas, on peut bien saisir des lettres (pas vraiment un problème pour nos utilisateurs).

2020-11-02 13:10 UTC, youf-olivier commented
Pensez au label UX meme sur les PR

2020-11-04 14:03 UTC, guillaume-chervet commented
@djaumes , du coup pour le champ date, il faudrait prendre le même comportement ?
ne plus permettre la saisie de caractères autre que ce attendu ?
Idem, faudrait-il bloquer la saisie des InputText si on dépasse la taille max attendu ?

je pense que c'est un vrai choix UX pas si anodin en conséquences, car le comportement doit être uniformisé sur tous les inputs.

2020-11-04 14:25 UTC, Railk commented
hello, je penses que ca mérite d'en parler de vive voix (point teams) UX/DEV pour lister tous les cas pour être bien sur qu'on oublie rien et être sur de notre choix.

2021-01-20 18:33 UTC, arnaudforaison approved these changes

2021-02-11 18:29 UTC, arnaudforaison commented
@djaumes et @Railk quelles sont les nouvelles sur ce composant number ?

2021-02-18 11:01 UTC, jforatier approved these changes

2021-02-18 11:02 UTC, merged