fix(versionBootstrap): put the version 4.3.1  bootstrap in the packag…
AxaGuilDEv/react-toolkit pull request #804
Opened 2020-11-13 16:49 UTC by DanneelsSophie

Related issue #764
Version
"version":"1.3.23"

Reference to the issue
Here you can add link to related issue

Description of the issue
Expected

![image](https://user-images.githubusercontent.com/15892424/99097860-7c175680-25d8-11eb-95c7-01abf0820889.png)
![image](https://user-images.githubusercontent.com/15892424/99097871-7faadd80-25d8-11eb-954b-bdadd1556ba6.png)
Additional Details

legacy boostrap with reboot.css and grid.css

Person(s) for reviewing proposed changes
@samuel-gomez @samuel-gomez-axa @xballoy

2020-11-13 16:56 UTC, samuel-gomez-axa approved these changes

2020-11-13 16:56 UTC, xballoy requested changes
Tu as des références au Nexus AXA dans ton package-lock.json

2020-11-13 16:56 UTC, xballoy commented on package-lock.json
> +          "resolved": "https://afa-nrepo.azure-paas.intraxa/repository/npmjs-group/fsevents/-/fsevents-1.2.13.tgz",
Tu as une référence au nexus axa

2020-11-15 17:59 UTC, samuel-gomez approved these changes

2020-11-16 08:05 UTC, xballoy approved these changes

2020-11-16 09:01 UTC, arnaudforaison approved these changes

2020-11-16 09:02 UTC, merged