build: add github action ci
AxaGuilDEv/react-toolkit pull request #842
Opened 2021-01-24 09:59 UTC by jforatier

## Related issue
Fixes #841 

### Reference to the issue

Not fix but GH-Action to check

### Description of the issue

`A GitHub action implementation to validate/check npm install / npm test (on push and PR)`

### Person(s) for reviewing proposed changes

`You can add @mention here`

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

2021-01-27 08:55 UTC, arnaudforaison commented
Bonne initiative, je pense qu'il faut intégrer ça. Etude en cours ;-)

2021-02-12 16:31 UTC, arnaudforaison requested changes

2021-02-12 16:31 UTC, arnaudforaison commented on .github/workflows/ci.yml
> +on: [push, pull_request]
```suggestion
on: 
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**
```

2021-02-12 17:08 UTC, arnaudforaison approved these changes

2021-02-17 08:48 UTC, bernard-arnaud approved these changes

2021-03-03 14:59 UTC, LunarzFR submitted a review, later dismissed

2021-03-04 10:17 UTC, arnaudforaison requested changes

2021-03-04 10:17 UTC, arnaudforaison commented on .github/workflows/ci.yml
> +      - run: npm install
npm ci

2021-03-04 10:17 UTC, arnaudforaison commented on .github/workflows/ci.yml
> +name: Toolkit - Build & Test
Changer le nom en `Compatibility npm on multi OS & Node version` + renommer le fichier en `compatibility-npm.yml`

2021-03-04 10:43 UTC, arnaudforaison approved these changes

2021-03-08 08:52 UTC, merged