feat(FileInput): reduce InputFile browse button width
AxaGuilDEv/react-toolkit pull request #846
Opened 2021-02-03 11:13 UTC by LunarzFR

Fixes #834 

_Before_
![image](https://user-images.githubusercontent.com/32737387/106739262-39827a80-6619-11eb-8ab6-ad74621968ac.png)

_After_
![image](https://user-images.githubusercontent.com/32737387/106739308-443d0f80-6619-11eb-8360-53f3cc689d2e.png)

2021-02-05 13:30 UTC, johnmeunier submitted a review, later dismissed

2021-02-11 11:00 UTC, jforatier approved these changes

2021-02-11 11:03 UTC, arnaudforaison requested changes
Est ce que flex-basis 100% est nécessaire ? Si la ligne est supprimée cela devrait fonctionner

2021-02-11 11:03 UTC, djaumes approved these changes

2021-02-15 08:43 UTC, LunarzFR commented
> Est ce que flex-basis 100% est nécessaire ? Si la ligne est supprimée cela devrait fonctionner

Si je ne mets pas le flex-basis à 100%, les pointillés ne font pas jusqu'au bout :
![image](https://user-images.githubusercontent.com/32737387/107923720-2c974c80-6f72-11eb-959b-2d791614b9bc.png)

2021-02-15 13:54 UTC, arnaudforaison commented
Je pense qu'il suffit de mettre un `flex: 1` à la place

2021-02-15 14:19 UTC, LunarzFR commented
> Je pense qu'il suffit de mettre un `flex: 1` à la place

En effet ;)

2021-02-15 14:23 UTC, djaumes approved these changes

2021-02-15 15:49 UTC, arnaudforaison approved these changes

2021-02-16 13:40 UTC, merged