[Doc] Ajout d'une section 'How to make and test a change in my context'
AxaGuilDEv/react-toolkit pull request #896
Opened 2021-03-16 10:47 UTC by jforatier

Hello,
J'avais besoin de pouvoir tester la version du toolkit dans mon projet en cours pour tester des fix ou des modifications, j'ai découvert pas mal de chose pour y arriver (merci @arnaudforaison). Je vous propose une petite mise à jour du Guide de Contribution avec le modop que j'ai suivi.

Si vous pouviez le tester de votre côté pour s'assurer qu'il n'y a pas de coquilles ça serait top 👍

2021-03-16 15:03 UTC, arnaudforaison requested changes
Est ce que ce super descriptif ne devrait pas être dans un DEVELOPER.md et que le contributing y fera référence ?

2021-03-16 15:03 UTC, arnaudforaison commented on CONTRIBUTING.md
> +    - run `npm run prepare` (you can click on arrow in vscode)
```suggestion
    - run `npm run prepare` (you can right-click on command & choose 'Run script' in vscode)
```

2021-03-18 08:08 UTC, samuel-gomez-axa commented on CONTRIBUTING.md
> +> More info about local install command [doc npm](https://docs.npmjs.com/cli/v7/commands/npm-install)
pensez-vous qu'il serait utile d'ajouter dans les pré-requis, la version de npm (v7 en l'occurence) ?

2021-03-18 12:11 UTC, Sebo1000 commented on CONTRIBUTING.md
> +
Que penses tu de rajouter une section afin d'indiquer comment mettre à jour le storyshot d'un composant ?

2021-03-18 12:11 UTC, Sebo1000 commented on CONTRIBUTING.md
> +      ```
```suggestion
      ...
```

2021-03-18 12:11 UTC, Sebo1000 commented on CONTRIBUTING.md
> +- Add a component file _MyProjectButton.js_ into your project with following content :
C'est possible de remplacer par `MyProjectButton.ts` histoire de rester dans l'air du temps ?! 😉

2021-03-18 12:11 UTC, Sebo1000 commented on CONTRIBUTING.md
> +> Considering you want to make changes on button
C'est voulu le chevron à ce niveau de la doc ?

2021-03-18 13:28 UTC, jforatier commented on CONTRIBUTING.md
> +
L'idée de cette partie c'était 'Je me lance et je teste un truc dans mon projet' néanmoins je voulais aussi faire une partie 'Préparer ma contribution' avec notamment la partie Test/Storybook. Je pensais me rattacher sur un bout de doc quelque part (ici ou ailleurs)

2021-03-18 13:29 UTC, jforatier commented on CONTRIBUTING.md
> +> More info about local install command [doc npm](https://docs.npmjs.com/cli/v7/commands/npm-install)
Je pense pas que la version joue ? Tu parles d'un prérequis générale au toolkit ou à la démarche que je soumet ?

2021-03-18 13:31 UTC, jforatier commented on CONTRIBUTING.md
> +- Fork toolkit (considering you want to submit your changes 👍) following [contributing guide](#installation)
Je voulais trouver un moyen de dire, la cible c'est de soumettre une proposition en fin d'exercice mais le sujet c'est quand même de 'faire fonctionner' en priorité. Je suis preneur de suggestions de présentation :-)

2021-03-18 15:26 UTC, samuel-gomez-axa approved these changes

2021-03-18 15:56 UTC, jforatier commented
> Est ce que ce super descriptif ne devrait pas être dans un DEVELOPER.md et que le contributing y fera référence ?

Idée à creuser, peut-être croiser les idées et regarder un peu ce qui se fait de bien en ce moment ? A dissocier dans une autre PR non ?

2021-03-18 15:58 UTC, jforatier commented on CONTRIBUTING.md
> +> Considering you want to make changes on button
Je sais pas ça rendait bien en preview :-)

2021-03-18 17:09 UTC, arnaudforaison commented
Oui cela sera splitté dans une autre PR

2021-03-19 09:38 UTC, samuel-gomez-axa commented on CONTRIBUTING.md
> +> More info about local install command [doc npm](https://docs.npmjs.com/cli/v7/commands/npm-install)
prérequis général, au même titre que la version de Node mais ce n'est peut-être pas utile

2021-03-23 09:24 UTC, arnaudforaison commented on CONTRIBUTING.md
> +- Fork toolkit (considering you want to submit your changes 👍) following [contributing guide](#installation)
Enlever la partie redondante (22 à 24)

2021-03-23 09:24 UTC, arnaudforaison commented on CONTRIBUTING.md
> +> Considering you want to make changes on button
Pour de la cohérence, mettre tous les descriptifs de paragraphe au même format

2021-03-25 15:18 UTC, arnaudforaison requested changes

2021-03-25 15:18 UTC, arnaudforaison commented on docs/DEVELOPER.md
> +[see Contributing](./../CONTRIBUTING.md)
```suggestion
[see Contributing](./../CONTRIBUTING.md#installation)
```

2021-03-25 15:18 UTC, arnaudforaison commented on docs/DEVELOPER.md
> +- `npm install -D sass` (optional - only if you want to use sass file from toolkit)
```suggestion
- `npm install -D sass` 
> Optional - only if you want to use sass file from toolkit
```

2021-03-25 15:18 UTC, arnaudforaison commented on docs/DEVELOPER.md
> +> Considering you want to make changes on button
```suggestion
Considering you want to make changes on button
```

2021-03-25 15:18 UTC, arnaudforaison commented on docs/DEVELOPER.md
> +    - run `npm run style` (you can click on arrow in vscode)
Je ne comprends pas trop ce que c'est 'arrow' du moins je ne visualise pas

2021-04-20 09:23 UTC, merged