Feature/storybook delete addon knobs
AxaGuilDEv/react-toolkit pull request #934
Opened 2021-11-11 15:33 UTC by samuel-gomez-axa

## Related issue 
#933 

### Description of the issue
rewrite stories and delete package addon-knobs

2021-11-14 07:50 UTC, arnaudforaison requested changes

2021-11-14 07:50 UTC, arnaudforaison commented on .storybook/main.js
> +    '@storybook/addon-storysource',
Pourquoi cet addon ? Est ce que le code source n'est pas suffisant ?

2021-11-14 07:50 UTC, arnaudforaison commented on .storybook/preview-body.html
> +<style>
Est ce que cette surcharge ne pourrait pas être dans le css ?

2021-11-14 07:50 UTC, arnaudforaison commented on jest.config.ts
>      '!packages/**/src/index.{js,ts}',
Est ce que cette ligne n'est pas incluse dans la nouvelle ?

2021-11-14 07:50 UTC, arnaudforaison commented on packages/Form/Input/date-phone/src/DatePhoneInput.stories.js
> +const stories = storiesOf('Form elements/Datephone', module);
Ne doit plus être écrit sous cette forme mais avec le export default

2021-11-14 07:50 UTC, arnaudforaison commented on packages/Form/Input/date-phone/src/DatePhoneInput.stories.js
> +const commonProps = {
Passage en écriture template plutôt, non ?

2021-11-14 07:50 UTC, arnaudforaison commented on packages/Form/Input/file/src/FileInput.stories.tsx
> +};
```suggestion
FileInputStoryRequired.args = {
 ...FileInputStory.args ,
  classModifier: 'required'
};
```

2021-11-16 09:10 UTC, samuel-gomez commented on packages/Form/Input/date-phone/src/DatePhoneInput.stories.js
> +const stories = storiesOf('Form elements/Datephone', module);
je n'ai pas changé cette story, car il faut d'abord passer le composant en TS

2021-11-16 09:10 UTC, samuel-gomez commented on packages/Form/Input/date-phone/src/DatePhoneInput.stories.js
> +const commonProps = {
Ici, j'ai juste voulu supprimer les knobs, je referai la story quand le composant sera passer en TS

2021-11-16 09:13 UTC, samuel-gomez commented on jest.config.ts
>      '!packages/**/src/index.{js,ts}',
je n'ai pas compris la question ^^

2021-11-16 09:15 UTC, samuel-gomez commented on .storybook/main.js
> +    '@storybook/addon-storysource',
je l'ai ajouté pour que les dev puissent avoir la source aussi lorsqu'ils sont sur l'onglet canvas (ça évite de devoir switcher à chaque fois)

2021-11-16 16:10 UTC, arnaudforaison approved these changes

2021-11-18 08:05 UTC, merged