feat(Restitution): allow ReactNode in value
AxaGuilDEv/react-toolkit pull request #946
Opened 2022-01-28 15:27 UTC by MartinWeb

## Related issue

### Reference to the issue

https://github.com/AxaGuilDEv/react-toolkit/issues/945

### Description of the issue

`Your description`

### Person(s) for reviewing proposed changes

`You can add @mention here`

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

2022-01-28 15:44 UTC, arnaudforaison requested changes

2022-01-28 15:44 UTC, arnaudforaison commented on packages/restitution/src/Restitution.tsx
> +  value?: string | React.ReactNode;
```suggestion
  value?: string | ReactNode;
```
Et donc faire l'import nécessaire sans passer par le global React

2022-01-28 16:08 UTC, MartinWeb commented on packages/restitution/src/Restitution.tsx
> +  value?: string | React.ReactNode;
Pris en compte, merci !

2022-01-31 08:16 UTC, romuleald commented
Peux-tu ajouter ajouter des cas d'usage dans le readme ?

2022-01-31 08:26 UTC, Aiso786 commented
Pas de Storybook sur ce composant ?

2022-01-31 08:31 UTC, MartinWeb commented
> Peux-tu ajouter ajouter des cas d'usage dans le readme ?

2022-01-31 08:42 UTC, MartinWeb commented
> Peux-tu ajouter ajouter des cas d'usage dans le readme ?

@romuleald  Le fichier readme a été modifié avec un cas d'usage de la modification. Attends-tu quelque chose de plus ?

2022-01-31 08:43 UTC, MartinWeb commented
> Pas de Storybook sur ce composant ?

@Aiso786 j'ai modifié le Storybook du composant pour ajouter un cas d'usage de l'utilisation du ReactNode en value. Tu peux le voir dans les fichiers modifiés. N'hésite pas à me dire si tu souhaiterais quelque chose de plus.

2022-01-31 09:05 UTC, Aiso786 commented
> > Pas de Storybook sur ce composant ?
> 
> @Aiso786 j'ai modifié le Storybook du composant pour ajouter un cas d'usage de l'utilisation du ReactNode en value. Tu peux le voir dans les fichiers modifiés. N'hésite pas à me dire si tu souhaiterais quelque chose de plus.

Ah oui, c'est bon, désolé je n'avais pas bien regardé.

2022-02-04 15:53 UTC, arnaudforaison requested changes
Je pense qu'il y a un débat à avoir pour savoir si on garde encore value ET values

2022-02-04 15:53 UTC, arnaudforaison commented on packages/restitution/src/Restitution.tsx
> +  value?: string | ReactNode;
ReactNode possède déjà le type string donc ça fait doublon
```suggestion
  value?: ReactNode;
```

2022-02-23 14:32 UTC, MartinWeb commented on packages/restitution/src/Restitution.tsx
> +  value?: string | ReactNode;
C'est fait, merci pour ta remarque.

2022-02-23 14:33 UTC, MartinWeb commented
@arnaudforaison nous avons fait le point avec @samuel-gomez, on conserve value et values pour le moment et on refactorera cette partie dans un second temps. Je loggue l'issue sur ce sujet une fois la PR validée.

2022-02-23 15:17 UTC, samuel-gomez-axa approved these changes

2022-02-24 10:01 UTC, arnaudforaison approved these changes

2022-02-24 14:38 UTC, merged