refactor(Restitution): add children property and export RestitutionVa…
AxaGuilDEv/react-toolkit pull request #950
Opened 2022-03-04 10:17 UTC by MartinWeb

### Reference to the issue
https://github.com/AxaGuilDEv/react-toolkit/issues/949 

### Description of the issue

Following allowing ReactNode in value of Restitution (https://github.com/AxaGuilDEv/react-toolkit/issues/945) properties value and values overlap.
The goal is now to keep only one of the two property.

For example, we can keep value and delete values but export the RestitutionValues component that is used when values is passed in order to let the consumer use that component as children of Restitution.

### Person(s) for reviewing proposed changes

@samuel-gomez

2022-03-07 08:30 UTC, MartinWeb commented on packages/restitution/src/RestitutionValues.tsx
> +const RestitutionValues = ({ values }: RestitutionValuesProps) => {
Oui, c'est encore mieux. Je pars là-dessus. 
Tu as d'autres remarques à part celle-là @samuel-gomez-axa  ?

2022-03-07 08:41 UTC, samuel-gomez-axa commented on packages/restitution/src/RestitutionValues.tsx
> +const RestitutionValues = ({ values }: RestitutionValuesProps) => {
non pour le reste, tout me semble ok :)
On en est où sur le pourcentage de couverture de test de ce composant @MartinWeb ?

2022-03-07 09:10 UTC, samuel-gomez-axa commented on packages/restitution/src/RestitutionValues.tsx
> +const RestitutionValues = ({ values }: RestitutionValuesProps) => {
parfait !

2022-03-07 09:11 UTC, samuel-gomez-axa approved these changes

2022-03-07 09:12 UTC, MartinWeb commented on packages/restitution/src/RestitutionValues.tsx
> +const RestitutionValues = ({ values }: RestitutionValuesProps) => {
C'est commité, je te laisse jeter un nouveau coup d'oeil si tu veux. Est-ce que je partage côté COP pour avoir plus de retour ?

2022-03-07 11:59 UTC, samuel-gomez-axa commented on packages/restitution/src/RestitutionValues.tsx
> +const RestitutionValues = ({ values }: RestitutionValuesProps) => {
yes, @arnaudforaison connait aussi le sujet, un deuxième avis c'est toujours mieux :)

2022-03-07 13:34 UTC, arnaudforaison requested changes

2022-03-07 13:34 UTC, arnaudforaison commented on packages/restitution/src/RestitutionList.tsx
> +};
```suggestion
type RestitutionListProps = ComponentPropsWithoutRef<"ul"> & {
  values: string[];
};
```

2022-03-07 13:34 UTC, arnaudforaison commented on packages/restitution/src/RestitutionList.tsx
> +  return <ul className="af-restitution__listul">{li}</ul>;
```suggestion
  return <ul className="af-restitution__listul" {...props}>{li}</ul>;
```

2022-03-08 13:01 UTC, samuel-gomez-axa commented on packages/restitution/src/RestitutionList.tsx
> +  const li = values.map((v: string) => (
c'est possible de mettre 'value' au lieu de 'v' ?

2022-03-08 13:05 UTC, MartinWeb commented on packages/restitution/src/RestitutionList.tsx
> +  const li = values.map((v: string) => (
Oui sans soucis :)

2022-03-08 14:25 UTC, samuel-gomez-axa approved these changes

2022-03-24 08:44 UTC, MartinWeb commented
@arnaudforaison j'ai pris en compte tes retours, si tu peux jeter à nouveau un coup d'oeil s'il te plait :) Merci

2022-04-07 09:05 UTC, arnaudforaison approved these changes

2022-04-08 08:49 UTC, merged