fix(Restitution): add classModifier to ArticleRestitution and univers…
AxaGuilDEv/react-toolkit pull request #959
Opened 2022-04-01 14:55 UTC by MartinWeb

### Reference to the issue

[`Here you can add link to related issue`](https://github.com/AxaGuilDEv/react-toolkit/issues/958)

### Description of the issue

The component Restitution doesn't allow a classModifier for the header to be styled according to the different universes colors (like component table for example).

2022-04-08 08:39 UTC, Debaerdm approved these changes

2022-04-08 08:47 UTC, arnaudforaison requested changes

2022-04-08 08:47 UTC, arnaudforaison commented on packages/restitution/src/ArticleRestitution.tsx
```suggestion
type ArticleRestitutionProps = ArticleRestitutionBaseProps & {
   classModifier?: string
};
```

2022-04-08 08:47 UTC, arnaudforaison commented on packages/restitution/src/ArticleRestitution.tsx
> +type ArticleRestitutionBaseProps = HTMLProps<HTMLElement>;
```suggestion
type ArticleRestitutionBaseProps = ComponentPropsWithoutRef<'article'>;
```

2022-04-08 08:47 UTC, arnaudforaison commented on packages/restitution/src/restitution.scss
> +    @include generate-universes() {
@samuel-gomez J'avais cru que les univers ne devaient plus être utilisés ?

2022-04-12 07:31 UTC, MartinWeb commented on packages/restitution/src/restitution.scss
> +    @include generate-universes() {
@arnaudforaison mon UX m'a glissé dans l'oreille que dans le futur toutes les appli seraient sur la même couleur, donc qu'on aurait plus du tout d'univers. Tu confirmes ? Est-ce que je modifie la PR dans ce sens pour ne garder que la possibilité d'utiliser le classModifier ?

2022-04-12 13:50 UTC, MartinWeb commented on packages/restitution/src/restitution.scss
> +    @include generate-universes() {
Banco @arnaudforaison  je fais ça

2022-04-12 20:16 UTC, samuel-gomez commented on packages/restitution/src/restitution.scss
> +    @include generate-universes() {
je confirme :)

2022-04-13 15:20 UTC, MartinWeb commented on packages/restitution/src/ArticleRestitution.tsx
done :)

2022-04-13 15:20 UTC, MartinWeb commented on packages/restitution/src/ArticleRestitution.tsx
> +type ArticleRestitutionBaseProps = HTMLProps<HTMLElement>;
done :)

2022-04-13 15:20 UTC, MartinWeb commented on packages/restitution/src/restitution.scss
> +    @include generate-universes() {
J'ai poussé les derniers changements @arnaudforaison  @samuel-gomez

2022-04-29 08:57 UTC, arnaudforaison approved these changes

2022-04-29 08:57 UTC, samuel-gomez-axa approved these changes

2022-04-29 08:59 UTC, samuel-gomez-axa approved these changes

2022-08-02 07:48 UTC, MartinWeb commented
@arnaudforaison @samuel-gomez-axa J'ai résolu le conflit qu'il y avait sur cette PR. Je pense qu'on peut également la prendre pour la future v2 si ça vous va :)

2022-08-05 13:36 UTC, arnaudforaison requested changes

2022-08-05 13:36 UTC, arnaudforaison commented on packages/restitution/src/ArticleRestitution.tsx
>    className,
```suggestion
  className,
  classModifier: _classModifier,
```

2022-08-05 13:36 UTC, arnaudforaison commented on packages/restitution/src/ArticleRestitution.tsx
>    className,
Cela permet d'omit classModifier pour éviter que cette props soit utilisé comme attributs de article (dans le DOM)

2022-08-05 14:42 UTC, arnaudforaison approved these changes

2022-08-05 14:42 UTC, merged